import { LogisticsRow, DbItem, SupplierItem, OrderStatus } from '../../types';
import { recalculateRow } from '../../utils';

export function buildNewLogisticsRow(
  nextId: number,
  draft: Partial<LogisticsRow>,
  dbItems: DbItem[],
  suppliers: SupplierItem[]
): LogisticsRow {
  const base: LogisticsRow = {
    id: nextId,
    orderDate: draft.orderDate || '2026-09-29',
    itemCode: draft.itemCode || 'CHK-01',
    itemName: draft.itemName || '',
    qty: Number(draft.orderedQty) || 0,
    uom: draft.uom || 'կգ',
    supplierCode: draft.supplierCode || 'SUP-101',
    supplierName: draft.supplierName || '',
    exporterName: '',
    brandName: '',
    orderedQty: Number(draft.orderedQty) || 0,
    unitPrice: Number(draft.unitPrice) || 0,
    currency: draft.currency || 'USD',
    totalAmount: 0,
    freightCostUSD: 4500,
    proformaNo: `PI-${nextId}`,
    proformaDate: '2026-09-29',
    productionDeadline: '',
    expirationDate: '',
    docProductionDate: '',
    docExpirationDate: '',
    prepaymentPct: Number(draft.prepaymentPct) || 0.3,
    prepaymentTerms: 'CAD',
    prepaymentDays: 5,
    finalPaymentPct: 0.7,
    finalPaymentTerms: 'Balance on arrival',
    finalPaymentDays: 14,
    prepaymentAmount: 0,
    prepaymentDate: '',
    prepaymentConfirmDate: '',
    interimAmount: 0,
    interimDate: '',
    warehouseEntryDate: '',
    containerPlannedLoadingDate: '',
    containerActualLoadingDate: '',
    exportCountry: 'Brazil',
    dispatchInstructions: '',
    cargoPhotosReceived: 'YES',
    transportMode: 'Maritime',
    containerNo: `MSKU${Math.floor(1000000 + Math.random() * 9000000)}`,
    plannedLoadingDate2: '',
    departureDateETD: '',
    currentDailyStatus: 'Order Created',
    istanbulArrivalDate: '',
    istanbulDepartureDate: '',
    potiPlannedEta: '2026-10-20',
    potiActualArrival: '',
    containerPickupDate: '',
    containerReturnDate: '',
    freeDaysCount: 21,
    secondaryDocsDate: '',
    courierCompany: '',
    courierTrackingNo: '',
    originalDocsDate: '',
    docsHandoverDate: '',
    invoiceNo: '',
    invoiceDate: '',
    invoicedQty: Number(draft.orderedQty) || 0,
    invoicedAmount: 0,
    retentionAmount: 0,
    finalPaymentAmount: 0,
    plannedFinalPaymentDate: '',
    actualFinalPaymentDate: '',
    finalPaymentConfirmDate: '',
    plannedCustomsEntryDate: '',
    customsDeclarationNo: '',
    customsRegDate: '',
    customsReleaseDate: '',
    customsPaymentDate: '',
    freightCarrier: 'Trans Caucasus Logistics',
    hsCode: '0207.14.10',
    transportExpense: 3200,
    status: (draft.status as OrderStatus) || 'Ճանապարհին',
    category: 'Chicken',
  };

  return recalculateRow(base, dbItems, suppliers);
}
